---
apiVersion: v1
kind: Namespace
metadata:
  name: kapture-control
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kapture-test-admin
  namespace: kapture-control
subjects:
- kind: ServiceAccount
  name: kapture-service-account
  namespace: kapture-control
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kapture
  name: kapture-service-account
  namespace: kapture-control
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kapture-config
  namespace: kapture-control
  labels:
    config: kapture
data:
  kapture_config: |
    action: create
    kafka:
      usePersistentVolume: False
    loadGen:
      bpsReplicas: 0
    namespace: test
---
apiVersion: v1
kind: Pod
metadata:
  name: control
  namespace: kapture-control
spec:
  serviceAccountName: kapture-service-account
  restartPolicy: Never
  containers:
  - name: kapture-control
    imagePullPolicy: Always
    image: carbonrelay/kapture:dev-storage
    command:
      - bash
      - -c
      - "python3 kapture/kapture.py"
    envFrom:
      - configMapRef:
          name: kapture-config
---
