#!/bin/bash

#!/bin/bash

set -e

BASEDIR=$(dirname $0)

(
	cd $BASEDIR

    if [[ ! -z "$(command -v python3)" ]]; then
		python_command=python3
	elif [[ ! -z $(command -v python) ]]; then
		python_command=python
	elif [[ ! -z $(command -v py) ]]; then
		python_command=py
	else
		echo "Unable to locate python on this machine.  Please install python or provide a path to a python installation on your machine to use the benchmark tool."
		exit 1
	fi

	$python_command kapture.py "$@"
)


exit 0

# Created by argbash-init v2.8.0
# Rearrange the order of options below according to what you would like to see in the help message.
# ARG_OPTIONAL_SINGLE([stores],[s],[Number of stores to initialize the BigPetStore with.  Will correspond to the number of Kafka topcis that will be generated],[250])
# ARG_OPTIONAL_SINGLE([customers],[c],[Number of customers to simulate for BigPetStore],[5000])
# ARG_OPTIONAL_SINGLE([simulation],[d],[Time (in days) to run the BigPetStore simulation over],[1500]))
# ARG_OPTIONAL_SINGLE([redis-count],[],[Number of Redis instances to cluster.  This option will be ignored unless deploy-redis is set to true.],[3]))
# ARG_OPTIONAL_BOOLEAN([delete],[],[Deletes all the kubernetes resources generated by a normal run],[off])
# ARG_OPTIONAL_BOOLEAN([deploy-prometheus],[p],[Deploy Prometheus as part of the cluster.],[off])
# ARG_OPTIONAL_BOOLEAN([deploy-redis],[r],[Deploy Redis (and the connector) as part of the cluster],[off])
# ARG_OPTIONAL_BOOLEAN([deploy-elastic-search],[e],[Deploy Elastic search (and the connector) as part of the cluster],[off])
# ARG_OPTIONAL_BOOLEAN([deploy-postgres],[o],[Deploy Postgres (and the Kafka connector) as part of the cluster.],[off])
# ARG_POSITIONAL_SINGLE([namespace],[The namespace to deploy Kapture to],[])
# ARG_POSITIONAL_SINGLE([load-gen-count],[Number of load generators to create to place load on the cluster],[0])
# ARG_DEFAULTS_POS()
# ARG_HELP([This script configures a cluster to run Kapture.])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.8.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info


die()
{
	local _ret=$2
	test -n "$_ret" || _ret=1
	test "$_PRINT_HELP" = yes && print_help >&2
	echo "$1" >&2
	exit ${_ret}
}


begins_with_short_option()
{
	local first_option all_short_options='scdpreoh'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_namespace=
_arg_load_gen_count="0"
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_stores="250"
_arg_customers="5000"
_arg_simulation="1500"
_arg_redis_count="3"
_arg_delete="off"
_arg_deploy_prometheus="off"
_arg_deploy_redis="off"
_arg_deploy_elastic_search="off"
_arg_deploy_postgres="off"


print_help()
{
	printf '%s\n' "This script configures a cluster to run Kapture."
	printf 'Usage: %s [-s|--stores <arg>] [-c|--customers <arg>] [-d|--simulation <arg>] [--redis-count <arg>] [--(no-)delete] [-p|--(no-)deploy-prometheus] [-r|--(no-)deploy-redis] [-e|--(no-)deploy-elastic-search] [-o|--(no-)deploy-postgres] [-h|--help] <namespace> [<load-gen-count>]\n' "$0"
	printf '\t%s\n' "<namespace>: The namespace to deploy Kapture to"
	printf '\t%s\n' "<load-gen-count>: Number of load generators to create to place load on the cluster (default: '0')"
	printf '\t%s\n' "-s, --stores: Number of stores to initialize the BigPetStore with.  Will correspond to the number of Kafka topcis that will be generated (default: '250')"
	printf '\t%s\n' "-c, --customers: Number of customers to simulate for BigPetStore (default: '5000')"
	printf '\t%s\n' "-d, --simulation: Time (in days) to run the BigPetStore simulation over (default: '1500')"
	printf '\t%s\n' "--redis-count: Number of Redis instances to cluster.  This option will be ignored unless deploy-redis is set to true. (default: '3')"
	printf '\t%s\n' "--delete, --no-delete: Deletes all the kubernetes resources generated by a normal run (off by default)"
	printf '\t%s\n' "-p, --deploy-prometheus, --no-deploy-prometheus: Deploy Prometheus as part of the cluster. (off by default)"
	printf '\t%s\n' "-r, --deploy-redis, --no-deploy-redis: Deploy Redis (and the connector) as part of the cluster (off by default)"
	printf '\t%s\n' "-e, --deploy-elastic-search, --no-deploy-elastic-search: Deploy Elastic search (and the connector) as part of the cluster (off by default)"
	printf '\t%s\n' "-o, --deploy-postgres, --no-deploy-postgres: Deploy Postgres (and the Kafka connector) as part of the cluster. (off by default)"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-s|--stores)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_stores="$2"
				shift
				;;
			--stores=*)
				_arg_stores="${_key##--stores=}"
				;;
			-s*)
				_arg_stores="${_key##-s}"
				;;
			-c|--customers)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_customers="$2"
				shift
				;;
			--customers=*)
				_arg_customers="${_key##--customers=}"
				;;
			-c*)
				_arg_customers="${_key##-c}"
				;;
			-d|--simulation)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_simulation="$2"
				shift
				;;
			--simulation=*)
				_arg_simulation="${_key##--simulation=}"
				;;
			-d*)
				_arg_simulation="${_key##-d}"
				;;
			--redis-count)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_redis_count="$2"
				shift
				;;
			--redis-count=*)
				_arg_redis_count="${_key##--redis-count=}"
				;;
			--no-delete|--delete)
				_arg_delete="on"
				test "${1:0:5}" = "--no-" && _arg_delete="off"
				;;
			-p|--no-deploy-prometheus|--deploy-prometheus)
				_arg_deploy_prometheus="on"
				test "${1:0:5}" = "--no-" && _arg_deploy_prometheus="off"
				;;
			-p*)
				_arg_deploy_prometheus="on"
				_next="${_key##-p}"
				if test -n "$_next" -a "$_next" != "$_key"
				then
					begins_with_short_option "$_next" && shift && set -- "-p" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
				fi
				;;
			-r|--no-deploy-redis|--deploy-redis)
				_arg_deploy_redis="on"
				test "${1:0:5}" = "--no-" && _arg_deploy_redis="off"
				;;
			-r*)
				_arg_deploy_redis="on"
				_next="${_key##-r}"
				if test -n "$_next" -a "$_next" != "$_key"
				then
					begins_with_short_option "$_next" && shift && set -- "-r" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
				fi
				;;
			-e|--no-deploy-elastic-search|--deploy-elastic-search)
				_arg_deploy_elastic_search="on"
				test "${1:0:5}" = "--no-" && _arg_deploy_elastic_search="off"
				;;
			-e*)
				_arg_deploy_elastic_search="on"
				_next="${_key##-e}"
				if test -n "$_next" -a "$_next" != "$_key"
				then
					begins_with_short_option "$_next" && shift && set -- "-e" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
				fi
				;;
			-o|--no-deploy-postgres|--deploy-postgres)
				_arg_deploy_postgres="on"
				test "${1:0:5}" = "--no-" && _arg_deploy_postgres="off"
				;;
			-o*)
				_arg_deploy_postgres="on"
				_next="${_key##-o}"
				if test -n "$_next" -a "$_next" != "$_key"
				then
					begins_with_short_option "$_next" && shift && set -- "-o" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
				fi
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'namespace'"
	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require between 1 and 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 1 and 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_namespace _arg_load_gen_count "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


printf 'Value of --%s: %s\n' 'stores' "$_arg_stores"
printf 'Value of --%s: %s\n' 'customers' "$_arg_customers"
printf 'Value of --%s: %s\n' 'simulation' "$_arg_simulation"
printf "'%s' is %s\\n" 'delete' "$_arg_delete"
printf "'%s' is %s\\n" 'deploy-prometheus' "$_arg_deploy_prometheus"
printf "'%s' is %s\\n" 'deploy-redis' "$_arg_deploy_redis"
printf "'%s' is %s\\n" 'deploy-elastic-search' "$_arg_deploy_elastic_search"
printf "'%s' is %s\\n" 'deploy-postgres' "$_arg_deploy_postgres"
printf "Value of '%s': %s\\n" 'namespace' "$_arg_namespace"
printf "Value of '%s': %s\\n" 'load-gen-count' "$_arg_load_gen_count"
printf "Value of '%s': %s\\n" 'redis-count' "$_arg_redis_count"


export namespace=$_arg_namespace
export load_generators=$_arg_load_gen_count
export redis_count=$_arg_redis_count
export customers=$_arg_customers
export simulation_time=$_arg_simulation
export stores=$_arg_stores
export deploy_prometheus=$_arg_deploy_prometheus
export deploy_redis=$_arg_deploy_redis
export deploy_elastic_search=$_arg_deploy_elastic_search
export deploy_postgres=$_arg_deploy_postgres
export delete=$_arg_delete

BASEDIR=$(dirname $0)

(
	cd $BASEDIR
	./scripts/kapture.sh
)
# ] <-- needed because of Argbash
