#!/bin/bash

# Created by argbash-init v2.8.0
# Rearrange the order of options below according to what you would like to see in the help message.
# ARG_OPTIONAL_SINGLE([stores],[s],[Number of stores to initialize the BigPetStore with.  Will correspond to the number of Kafka topcis that will be generated],[13])
# ARG_OPTIONAL_SINGLE([customers],[c],[Number of customers to simulate for BigPetStore],[500000])
# ARG_OPTIONAL_SINGLE([simulation],[d],[Time (in days) to run the BigPetStore simulation over],[15000])
# ARG_POSITIONAL_SINGLE([namespace],[The namespace to deploy Kapture to],[])
# ARG_DEFAULTS_POS()
# ARG_HELP([<The general help message of my script>])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.8.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info


die()
{
	local _ret=$2
	test -n "$_ret" || _ret=1
	test "$_PRINT_HELP" = yes && print_help >&2
	echo "$1" >&2
	exit ${_ret}
}


begins_with_short_option()
{
	local first_option all_short_options='scdh'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_namespace=
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_stores="13"
_arg_customers="500000"
_arg_simulation="15000"


print_help()
{
	printf '%s\n' "<The general help message of my script>"
	printf 'Usage: %s [-s|--stores <arg>] [-c|--customers <arg>] [-d|--simulation <arg>] [-h|--help] <namespace>\n' "$0"
	printf '\t%s\n' "<namespace>: The namespace to deploy Kapture to"
	printf '\t%s\n' "-s, --stores: Number of stores to initialize the BigPetStore with.  Will correspond to the number of Kafka topcis that will be generated (default: '13')"
	printf '\t%s\n' "-c, --customers: Number of customers to simulate for BigPetStore (default: '500000')"
	printf '\t%s\n' "-d, --simulation: Time (in days) to run the BigPetStore simulation over (default: '15000')"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-s|--stores)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_stores="$2"
				shift
				;;
			--stores=*)
				_arg_stores="${_key##--stores=}"
				;;
			-s*)
				_arg_stores="${_key##-s}"
				;;
			-c|--customers)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_customers="$2"
				shift
				;;
			--customers=*)
				_arg_customers="${_key##--customers=}"
				;;
			-c*)
				_arg_customers="${_key##-c}"
				;;
			-d|--simulation)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_simulation="$2"
				shift
				;;
			--simulation=*)
				_arg_simulation="${_key##--simulation=}"
				;;
			-d*)
				_arg_simulation="${_key##-d}"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'namespace'"
	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_namespace "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


printf 'Value of --%s: %s\n' 'stores' "$_arg_stores"
printf 'Value of --%s: %s\n' 'customers' "$_arg_customers"
printf 'Value of --%s: %s\n' 'simulation' "$_arg_simulation"
printf "Value of '%s': %s\\n" 'namespace' "$_arg_namespace"

# ] <-- needed because of Argbash

export namespace=$_arg_namespace
export customers=$_arg_customers
export simulation_time=$_arg_simulation
export stores=$_arg_stores
./scripts/kapture.sh
