---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics
spec:
  endpoints:
  - interval: 15s
    port: metrics
  selector:
    matchLabels:
      app: kafka
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-subscription-metrics
spec:
  endpoints:
  - interval: 15s
    port: metrics
  selector:
    matchLabels:
      app: rkconn
---
