---
apiVersion: v1
kind: Service
metadata:
  name: kafka-metrics-svc
  labels:
    metrics: kafka
spec:
  ports:
    - port: 8000
      name: metrics
  selector:
    metrics: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-metrics
  labels:
    metrics: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      metrics: kafka
  template:
    metadata:
      name: kafka-metrics
      labels:
        metrics: kafka
    spec:
      containers:
      - name: kafka-metrics
        image: carbonrelay/kapture:dev-alt-load-gen
        imagePullPolicy: Always
        command:
          - python3
          - /opt/kafka-metrics.py
        ports:
          - containerPort: 8000
---
