---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  template:
    spec:
      containers:
      - name: k8skafka
        env:
        - name: KAFKA_HEAP_OPTS
          value : "JAVA_MEMORY_OPTIONS"
        resources:
          limits:
            cpu: CPU_LIMIT
            memory: MEMORY_LIMIT
          requests:
            cpu: CPU_REQUEST
            memory: MEMORY_REQUEST
---
