---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
  PGDATA: /pgdata/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  # There should never be more than 1 replica of this pod due to the volume being ReadWriteOnce
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /pgdata
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-connector
  template:
    metadata:
      labels:
        app: postgres-connector
    spec:
      containers:
      - name: postgres-connector
        imagePullPolicy: Always
        image: carbonrelay/kapture:dev-postgresql
        command:
          - bash
          - -c
          - "./postgres-connector.sh"
        envFrom:
        - configMapRef:
            name: postgres-config
        env:
          - name: DB_HOST
            value: postgres-svc
          - name: BROKERS
            value: "kafka-svc:9093"
---
