---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics
spec:
  endpoints:
  - interval: 120s
    port: metrics
    scrapeTimeout: 60s
  selector:
    matchLabels:
      app: kafka
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-connector-metrics
spec:
  endpoints:
  - interval: 15s
    port: metrics
  selector:
    matchLabels:
      app: rkconn
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bps-metrics
spec:
  endpoints:
  - interval: 15s
    port: metrics
  selector:
    matchLabels:
      app: datagen
---
