---
apiVersion: v1
kind: Service
metadata:
  name: rkconn-svc
  labels:
    app: rkconn
spec:
  ports:
    - port: 7001
      targetPort: 7001
      name: metrics
  selector:
    app: rkconn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rkconn
spec:
  replicas: 0
  selector:
    matchLabels:
      app: rkconn
  template:
    metadata:
      labels:
        app: rkconn
    spec:
      containers:
      - name: redis-consumer
        imagePullPolicy: Always
        image: benfen/dummy-kafka-messenger:v0.4-dev
        env:
          - name: BROKERS
            value: "kafka-svc:9093"
          - name: GROUP_ID
            value: "redis-consumer"
          - name: MESSENGER_MODE
            value: "REDIS_LISTEN"
          - name: REDIS_HOST
            value: "redis-sentinel:26379"
        ports:
          - containerPort: 7001
---
