---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sentinel
    role: service
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 0
  selector:
    name: redis
    role: slave
  template:
    metadata:
      labels:
        name: redis
        role: slave
    spec:
      containers:
      - name: redis
        image: k8s.gcr.io/redis:v1
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        env:
          - name: MAX_MEMORY
            value: "50mb"
          - name: EVICTION_POLICY
            value: allkeys-lru
        command:
          - bash
          - -c
          - "printf \"maxmemory $MAX_MEMORY\nmaxmemory-policy $EVICTION_POLICY\" >> /redis-slave/redis.conf && /run.sh"
      volumes:
      - name: data
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
spec:
  replicas: 0
  selector:
    redis-sentinel: "true"
    role: sentinel
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
    spec:
      containers:
      - name: sentinel
        image: k8s.gcr.io/redis:v1
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
---