---
apiVersion: v1
kind: Service
metadata:
  name: rkconn-svc
  labels:
    app: rkconn
spec:
  ports:
    - port: 7001
      targetPort: 7001
      name: metrics
  selector:
    app: rkconn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rkconn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rkconn
  template:
    metadata:
      labels:
        app: rkconn
    spec:
      containers:
      - name: load-gen-consumer
        imagePullPolicy: Always
        image: benfen/dummy-kafka-messenger:0.1
        env:
          - name: BROKERS
            value: "kafka-svc:9093"
          - name: GROUP_ID
            value: "producer-${HOSTNAME##*-}"
          - name: MESSENGER_MODE
            value: "listen"
          - name: REDIS_HOST
            value: "redis-sentinel:26379"
          - name: STORE_COUNT
            valueFrom:
              configMapKeyRef:
                name: kapture-config
                key: STORE_COUNT
          - name: ZOOKEEPER_URL
            value: "zk-svc:2181"
        ports:
          - containerPort: 7001
---
