---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        env:
          - name: EVICTION_POLICY
            value: "noeviction"
        resources:
          limits:
            cpu: 0.1
---
