---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        env:
          - name: MAX_MEMORY
            value: "500000mb"
        resources:
          limits:
            cpu: 0.1
---
