---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-conf
data:
   logstash.conf: |
    input {
      kafka {
        bootstrap_servers => ["kafka-svc:9093"]
        decorate_events => true
        topics => ["bps-data"]
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "%{[@metadata][kafka][topic]}"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-yaml
data:
   logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    queue:
      type: persisted
      max_bytes: 2gb
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-svc
spec:
  selector:
    app: logstash
  ports:
  - port: 9600
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  serviceName: logstash
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-data
        image: docker.elastic.co/logstash/logstash:7.0.0
        ports:
        - containerPort: 9600
          name: transport
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: logstash-conf
          mountPath: /usr/share/logstash/config/logstash.conf
          subPath: logstash.conf
        - name: logstash-yaml
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        command:
          - bash
          - -c
          - "/usr/share/logstash/bin/logstash -f /usr/share/logstash/config/logstash.conf"
      volumes:
        - emptyDir:
            medium: ""
          name: storage
        - name: logstash-conf
          configMap:
            name: logstash-conf
        - name: logstash-yaml
          configMap:
            name: logstash-yaml
---